// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Eegy.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "eegy";





        [DllImport(__DllName, EntryPoint = "sample_func_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int sample_func_add(int a, int b);


    }



}
